# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Exchange": "00_exchange.ipynb",
         "Binance": "01_binance.ipynb",
         "BinanceAPI": "01_binance.ipynb",
         "Bitbank": "02_bitbank.ipynb",
         "Huobi": "03_huobi.ipynb",
         "HuobiSVC": "03_huobi.ipynb",
         "MXC": "04_mxc.ipynb",
         "MXCAPI": "04_mxc.ipynb",
         "Status": "10_status.ipynb",
         "Fetcher": "21_fetcher.ipynb",
         "Portfolio": "22_bookkeeper.ipynb",
         "BookKeeper": "22_bookkeeper.ipynb",
         "Trader": "main-mxc.ipynb",
         "TEST_RATIO": "main-mxc.ipynb",
         "NOTIFY_RATE": "main-mxc.ipynb",
         "BACKUP_RATE": "main-mxc.ipynb",
         "CRYPTO_SYMBOL": "main-ar.ipynb",
         "FIAT_SYMBOL": "main-ar.ipynb",
         "MAX_USED_FIAT_MONEY_LIMIT": "main-mxc.ipynb",
         "exchange": "main-mxc.ipynb",
         "fetcher": "main-mxc.ipynb",
         "notifier": "main-mxc.ipynb",
         "trading_spec": "main-ar.ipynb",
         "status": "main-ar.ipynb",
         "GAINABLE_UNIT_CC_SOLD_RATIO": "main-mxc.ipynb",
         "LOSSABLE_UNIT_CC_BOUGHT_RATIO": "main-mxc.ipynb",
         "MIN_TRADE_FIAT_PRICE": "main-mxc.ipynb",
         "MAX_TRADE_FIAT_PRICE": "main-mxc.ipynb",
         "ICON_URL": "main-bitbank.ipynb",
         "Status.robot_name_prefix": "main-mxc.ipynb",
         "messages": "main-mxc.ipynb",
         "color": "main-mxc.ipynb",
         "status_list": "main-mxc.ipynb",
         "Trader.SAMPLE_INTERVAL": "main-mxc.ipynb",
         "FIAT_SYMBOLS": "main-mxc.ipynb",
         "Notifier": "notifier.ipynb"}

modules = ["__init__.py",
           "ar.py",
           "binance.py",
           "bitbank.py",
           "huobi.py",
           "mxc.py",
           "secrets.py"]

doc_url = "https://seii-saintway.github.io/ccstabilizer/"

git_url = "https://github.com/seii-saintway/ccstabilizer/tree/master/"

def custom_doc_links(name): return None
