# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Binance": "binance.ipynb",
         "Portfolio": "bookkeeper.ipynb",
         "BookKeeper": "bookkeeper.ipynb",
         "Fetcher": "fetcher.ipynb",
         "TEST_RATIO": "main-mxc.ipynb",
         "NOTIFY_RATE": "main-mxc.ipynb",
         "BACKUP_RATE": "main-mxc.ipynb",
         "CRYPTO_SYMBOL": "main-ar.ipynb",
         "FIAT_SYMBOL": "main-ar.ipynb",
         "MAX_USED_FIAT_MONEY_LIMIT": "main-mxc.ipynb",
         "fetcher": "main-mxc.ipynb",
         "notifier": "main-mxc.ipynb",
         "symbol_in_mxc": "main-ar.ipynb",
         "crypto_info": "main-ar.ipynb",
         "status": "main-ar.ipynb",
         "FIAT_SYMBOLS": "main-mxc.ipynb",
         "GAINABLE_UNIT_CC_SOLD_RATIO": "main-mxc.ipynb",
         "LOSSABLE_UNIT_CC_BOUGHT_RATIO": "main-mxc.ipynb",
         "MIN_TRADE_FIAT_PRICE": "main-mxc.ipynb",
         "MAX_TRADE_FIAT_PRICE": "main-mxc.ipynb",
         "crypto_infos": "main-mxc.ipynb",
         "status_list": "main-mxc.ipynb",
         "trader_list": "main-mxc.ipynb",
         "notifier_list": "main-mxc.ipynb",
         "MXC": "mxc.ipynb",
         "Notifier": "notifier.ipynb",
         "Status": "status.ipynb",
         "Trader": "trader.ipynb"}

modules = ["__init__.py",
           "ar.py",
           "mxc.py",
           "secrets.py"]

doc_url = "https://seii-saintway.github.io/ccstabilizer/"

git_url = "https://github.com/seii-saintway/ccstabilizer/tree/master/"

def custom_doc_links(name): return None
